version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/HelloCircleCI
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install          